# Generated by Django 5.1.2 on 2024-10-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Length', models.CharField(max_length=100)),
                ('Width', models.CharField(max_length=100)),
                ('Height', models.CharField(max_length=100)),
                ('Wheel', models.CharField(max_length=100)),
                ('Boot_Space', models.CharField(max_length=100)),
                ('Seating_Capacity', models.CharField(max_length=100)),
                ('Turning_Radius', models.CharField(max_length=100)),
            ],
        ),
    ]
