# Generated by Django 5.1.2 on 2024-10-26 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoworld', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dimensions',
            old_name='Wheel',
            new_name='Wheelbase',
        ),
    ]
