# Generated by Django 5.1.2 on 2024-10-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoworld', '0002_rename_wheel_dimensions_wheelbase'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimensions',
            name='modelname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
