# Generated by Django 5.1.2 on 2024-10-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoworld', '0004_rename_modelname_dimensions_modelname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimensions',
            name='Boot_Space',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dimensions',
            name='Height',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dimensions',
            name='Length',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dimensions',
            name='Seating_Capacity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dimensions',
            name='Turning_Radius',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dimensions',
            name='Wheelbase',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dimensions',
            name='Width',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
