# Generated by Django 5.1.2 on 2024-10-29 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoworld', '0005_alter_dimensions_boot_space_alter_dimensions_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('view_count', models.IntegerField()),
                ('like_count', models.IntegerField()),
                ('comment_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('like_count', models.IntegerField()),
                ('sentiment', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=10, null=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='autoworld.youtubevideo')),
            ],
        ),
    ]
