# Generated by Django 5.1.2 on 2024-10-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoworld', '0007_alter_youtubecomment_sentiment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubecomment',
            name='category',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
