# Generated by Django 5.1.2 on 2024-10-30 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoworld', '0008_youtubecomment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='autoworld.dimensions'),
        ),
    ]
