# Generated by Django 5.1.2 on 2024-10-30 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoworld', '0009_youtubevideo_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=20, unique=True)),
                ('image_url', models.URLField()),
                ('caption', models.TextField()),
                ('like_count', models.IntegerField()),
                ('comment_count', models.IntegerField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_posts', to='autoworld.dimensions')),
            ],
        ),
        migrations.CreateModel(
            name='TwitterPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=20, unique=True)),
                ('content', models.TextField()),
                ('retweet_count', models.IntegerField()),
                ('like_count', models.IntegerField()),
                ('reply_count', models.IntegerField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twitter_posts', to='autoworld.dimensions')),
            ],
        ),
        migrations.CreateModel(
            name='InstagramComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('like_count', models.IntegerField()),
                ('sentiment', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Neutral', 'Neutral')], max_length=10, null=True)),
                ('category', models.CharField(max_length=10, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='autoworld.instagrampost')),
            ],
            options={
                'unique_together': {('post', 'text')},
            },
        ),
        migrations.CreateModel(
            name='TwitterComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('like_count', models.IntegerField()),
                ('sentiment', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Neutral', 'Neutral')], max_length=10, null=True)),
                ('category', models.CharField(max_length=10, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='autoworld.twitterpost')),
            ],
            options={
                'unique_together': {('post', 'text')},
            },
        ),
    ]
